export enum NotificationType {
  GOAL_MILESTONE = 'GOAL_MILESTONE',
  GOAL_COMPLETED = 'GOAL_COMPLETED',
  STUDY_REMINDER = 'STUDY_REMINDER',
  QUIZ_AVAILABLE = 'QUIZ_AVAILABLE',
  QUIZ_DEADLINE = 'QUIZ_DEADLINE',
  COURSE_UPDATE = 'COURSE_UPDATE',
  CALENDAR_EVENT = 'CALENDAR_EVENT',
  DEADLINE_REMINDER = 'DEADLINE_REMINDER',
  GPA_UPDATE = 'GPA_UPDATE',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION'
} 